version: "3"

services:
  # Redis
  redis:
    image: redis:latest
    container_name: redis_fans
    command: redis-server --dir /data
    restart: always
    volumes:
    - ./test_data/redis:/data
    ports:
    - 6379:6379

  # Mongo
  mongo:
    image: mongo
    container_name: mongodb_fans
    volumes:
    - ./test_data/mongodb:/var/lib/mongodb
    ports:
    - 27017:27017
